{
    'name': 'SBU Purchase Flow',
    'version': '19.0.1.0.13',
    'summary': 'RDA/ACP/ACO/LDS purchase requests; supplier comparison matrix, chosen offer → PO trace (3.5)',
    'author': 'SBU Development',
    'category': 'Purchase',
    'depends': [
        'base',
        'mail',
        'purchase',
        'stock',
        'project',
        'sbu_estimate',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sbu_purchase_request_sequence.xml',
        'views/sbu_purchase_request_views.xml',
        'views/sbu_purchase_request_offer_views.xml',
        'views/purchase_order_views.xml',
        'views/project_project_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
