{
    'name': 'SBU Purchase Flow',
    'version': '19.0.1.0.14',
    'summary': 'RDA/ACP/ACO/LDS purchase requests; PR→PO project link with sbu_stock_config (4.2)',
    'author': 'SBU Development',
    'category': 'Purchase',
    'depends': [
        'base',
        'mail',
        'purchase',
        'stock',
        'project',
        'sbu_estimate',
        'sbu_stock_config',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sbu_purchase_request_sequence.xml',
        'views/sbu_purchase_request_views.xml',
        'views/sbu_purchase_request_offer_views.xml',
        'views/purchase_order_views.xml',
        'views/project_project_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
