{
    'name': 'SBU SAL',
    'version': '19.0.1.0.54',
    'summary': 'Customer SAL, passive SAL (posa/subcontract), CDP and accounting',
    'author': 'SBU Development',
    'category': 'Accounting',
    'depends': [
        'base',
        'mail',
        'account',
        'project',
        'sbu_estimate',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sbu_sal_sequence.xml',
        'views/res_company_views.xml',
        'views/sbu_sal_views.xml',
        'views/sbu_sal_passive_views.xml',
        'views/sbu_estimate_sal_line_views.xml',
        'views/project_project_views.xml',
        'report/sbu_invoice_sal_report.xml',
        'views/account_move_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
